name:                schedule
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/TomLippincott/schedule#readme
license:             BSD3
author:              Tom Lippincott
maintainer:          tom@cs.jhu.edu
copyright:           2018 Tom Lippincott
category:            Web
extra-source-files:
- README.md

default-extensions:
  - Strict
  - StrictData
  - FlexibleContexts
  - RecordWildCards
  - MultiParamTypeClasses
  - FlexibleInstances
  - OverloadedStrings
  - ScopedTypeVariables

dependencies:
  - base >=4.7 && <5
  - text >=1.2.2
  - containers >=0.5.10.2  
  - sbv >=8.3
  - optparse-generic >=1.3.0
  - time >=1.9.2
  - gogol-sheets ==0.5.0
  - lens ==4.16
  - gogol ==0.5.0
  - aeson ==1.2.4.0
  - random >=1.1
  - bimap >=0.3.3
  - mime-mail >=0.5.0
  - bytestring >=0.10.10.1
  
ghc-options: -O0

library:
  source-dirs: src
  
executables:
  scheduler:
    source-dirs:      app
    main:             Main.hs
    dependencies:
      - schedule
